## Berry Config
## ============
## you'll also need to copy the auth details saved to your dev folder
## - cp ./.yarnrc.yml.auth-example ../.yarnrc.yml
## ensure to add your authToken which is likely to be in your .npmrc file

changesetIgnorePatterns:
  - "**/*.{test,spec}.{js,jsx,ts,tsx}"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

## More info:
## https://yarnpkg.com/advanced/error-codes/
logFilters:
  - code: YN0002
    level: discard
  - code: YN0007
    level: discard
  - code: YN0060
    level: discard
  - code: YN0076
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

npmScopes:
  clearscore:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://clearscoredev.jfrog.io/clearscoredev/api/npm/npm/"
    npmRegistryServer: "https://clearscoredev.jfrog.io/clearscoredev/api/npm/npm/"

defaultSemverRangePrefix: ""
