export default {
    testRegex: '\\.test\\.js',
    testURL: 'http://localhost',
    setupFiles: [],
    coverageDirectory: './.reports/coverage',
    collectCoverage: false,
    reporters: ['default', 'jest-junit'],
    roots: ['<rootDir>'],
    collectCoverageFrom: ['src/**/*.js', 'src/**/*.mjs'],
    testPathIgnorePatterns: [],
    moduleNameMapper: {},
    resetMocks: true,
    resetModules: true,
    restoreMocks: true,
};
